# -*- coding: utf-8 -*-

from core.conf import CONST



CATEGORIES = [
    {
        'name': '赛事', 'logo': CONST['static']['url']+'images/fifa/comprehensive/fifa.png',
        'tags': [ 
            { 'name': '中超',   'logo': CONST['static']['url']+'images/fifa/competition/csl.png' },
            { 'name': '英超',   'logo': CONST['static']['url']+'images/fifa/competition/epl.png' },
            { 'name': '意甲',   'logo': CONST['static']['url']+'images/fifa/competition/seriea.png' },
            { 'name': '西甲',   'logo': CONST['static']['url']+'images/fifa/competition/laliga.png' },
            { 'name': '德甲',   'logo': CONST['static']['url']+'images/fifa/competition/bundesliga.png' },
            { 'name': '法甲',   'logo': CONST['static']['url']+'images/fifa/competition/ligue1.png' },
            { 'name': '欧冠',   'logo': CONST['static']['url']+'images/fifa/competition/championsleague.png' },
            { 'name': '亚冠',   'logo': CONST['static']['url']+'images/fifa/competition/afccl.png' },
            { 'name': '中甲',   'logo': CONST['static']['url']+'images/fifa/competition/cl1.png' },
            #{ 'name': '欧洲杯', 'logo': CONST['static']['url']+'images/fifa/competition/uefaeuro.png' },
            #{ 'name': '美洲杯', 'logo': CONST['static']['url']+'images/fifa/competition/copaamerica.png' },
            #{ 'name': '欧联杯', 'logo': CONST['static']['url']+'images/fifa/competition/uel.png' },
            #{ 'name': '足总杯', 'logo': CONST['static']['url']+'images/fifa/competition/efacup.png' },
            #{ 'name': '亚洲杯', 'logo': CONST['static']['url']+'images/fifa/competition/asiancup.png' },
            #{ 'name': '足协杯', 'logo': CONST['static']['url']+'images/fifa/competition/cfacup.png' },
            #{ 'name': '世界杯', 'logo': CONST['static']['url']+'images/fifa/competition/worldcup.png' },
        ],                                               
    },                                                   
    {
        'name': '中超', 'logo': CONST['static']['url']+'images/fifa/competition/csl.png',
        'tags': [ 
            { 'name': '广州恒大',   'logo': CONST['static']['url']+'images/fifa/team/csl/gzhd.png' },
            { 'name': '上海上港',   'logo': CONST['static']['url']+'images/fifa/team/csl/shsg.png' },
            { 'name': '北京国安',   'logo': CONST['static']['url']+'images/fifa/team/csl/bjga.png' },
            { 'name': '山东鲁能',   'logo': CONST['static']['url']+'images/fifa/team/csl/sdln.png' },
            { 'name': '天津泰达',   'logo': CONST['static']['url']+'images/fifa/team/csl/tjtd.png' },
            { 'name': '江苏苏宁',   'logo': CONST['static']['url']+'images/fifa/team/csl/jssn.png' },
            { 'name': '河北华夏',   'logo': CONST['static']['url']+'images/fifa/team/csl/hbhx.png' },
            { 'name': '河南建业',   'logo': CONST['static']['url']+'images/fifa/team/csl/hnjy.png' },
            { 'name': '上海申花',   'logo': CONST['static']['url']+'images/fifa/team/csl/shsh.png' },
            { 'name': '重庆力帆',   'logo': CONST['static']['url']+'images/fifa/team/csl/cqlf.png' },
            { 'name': '长春亚泰',   'logo': CONST['static']['url']+'images/fifa/team/csl/ccyt.png' },
            { 'name': '辽宁宏远',   'logo': CONST['static']['url']+'images/fifa/team/csl/lnhy.png' },
            { 'name': '广州富力',   'logo': CONST['static']['url']+'images/fifa/team/csl/gzfl.png' },
            { 'name': '延边富德',   'logo': CONST['static']['url']+'images/fifa/team/csl/ybfd.png' },
            { 'name': '天津权健',   'logo': CONST['static']['url']+'images/fifa/team/cl1/tjqj.png' },
            { 'name': '贵州智诚',   'logo': CONST['static']['url']+'images/fifa/team/cl1/gzzc.png' },
        ],
    },
    {                                                    
        'name': '英超', 'logo': CONST['static']['url']+'images/fifa/competition/epl.png',
        'tags': [                                        
            { 'name': '曼联',       'logo': CONST['static']['url']+'images/fifa/team/epl/mu.png' },    
            { 'name': '切尔西',     'logo': CONST['static']['url']+'images/fifa/team/epl/che.png' },
            { 'name': '阿森纳',     'logo': CONST['static']['url']+'images/fifa/team/epl/ars.png' },
            { 'name': '利物浦',     'logo': CONST['static']['url']+'images/fifa/team/epl/liv.png' },
            { 'name': '曼城',       'logo': CONST['static']['url']+'images/fifa/team/epl/mc.png' },
            { 'name': '热刺',       'logo': CONST['static']['url']+'images/fifa/team/epl/tot.png' },
            { 'name': '莱斯特城',   'logo': CONST['static']['url']+'images/fifa/team/epl/lc.png' },
            { 'name': '埃弗顿',     'logo': CONST['static']['url']+'images/fifa/team/epl/afd.png' },
            { 'name': '水晶宫',     'logo': CONST['static']['url']+'images/fifa/team/epl/sjg.png' },
            { 'name': '伯恩茅斯',   'logo': CONST['static']['url']+'images/fifa/team/epl/bems.png' },
            { 'name': '赫尔城',     'logo': CONST['static']['url']+'images/fifa/team/epl/hec.png' },
            { 'name': '桑德兰',     'logo': CONST['static']['url']+'images/fifa/team/epl/sdl.png' },
            { 'name': '西布朗维奇', 'logo': CONST['static']['url']+'images/fifa/team/epl/sblwq.png' },
            { 'name': '斯旺西',     'logo': CONST['static']['url']+'images/fifa/team/epl/swx.png' },
            { 'name': '西汉姆联',   'logo': CONST['static']['url']+'images/fifa/team/epl/xhm.png' },
            { 'name': '南安普顿',   'logo': CONST['static']['url']+'images/fifa/team/epl/napd.png' },
            { 'name': '斯托克城',   'logo': CONST['static']['url']+'images/fifa/team/epl/stkc.png' },
            { 'name': '沃特福德',   'logo': CONST['static']['url']+'images/fifa/team/epl/wtfd.png' },
            { 'name': '伯恩利',     'logo': CONST['static']['url']+'images/fifa/team/epl/bel.png' },
            { 'name': '米德尔斯堡', 'logo': CONST['static']['url']+'images/fifa/team/epl/mdesb.png' },
        ],
    },
    {
        'name': '西甲', 'logo': CONST['static']['url']+'images/fifa/competition/laliga.png',
        'tags': [ 
            { 'name': '巴萨',           'logo': CONST['static']['url']+'images/fifa/team/laliga/fcb.png' },
            { 'name': '皇马',           'logo': CONST['static']['url']+'images/fifa/team/laliga/rm.png' },
            { 'name': '马竞',           'logo': CONST['static']['url']+'images/fifa/team/laliga/atm.png' },
            { 'name': '瓦伦西亚',       'logo': CONST['static']['url']+'images/fifa/team/laliga/val.png' },
            { 'name': '塞维利亚',       'logo': CONST['static']['url']+'images/fifa/team/laliga/sev.png' },
            { 'name': '比利亚雷亚尔',   'logo': CONST['static']['url']+'images/fifa/team/laliga/vil.png' },
            { 'name': '毕尔巴鄂竞技',   'logo': CONST['static']['url']+'images/fifa/team/laliga/bebejj.png' },
            { 'name': '塞尔塔',         'logo': CONST['static']['url']+'images/fifa/team/laliga/set.png' },
            { 'name': '马拉加',         'logo': CONST['static']['url']+'images/fifa/team/laliga/mlj.png' },
            { 'name': '埃瓦尔',         'logo': CONST['static']['url']+'images/fifa/team/laliga/awe.png' },
            { 'name': '拉科鲁尼亚',     'logo': CONST['static']['url']+'images/fifa/team/laliga/lklny.png' },
            { 'name': '皇家社会',       'logo': CONST['static']['url']+'images/fifa/team/laliga/hjsh.png' },
            { 'name': '西班牙人',       'logo': CONST['static']['url']+'images/fifa/team/laliga/xbyr.png' },
            { 'name': '皇家贝蒂斯',     'logo': CONST['static']['url']+'images/fifa/team/laliga/hjbds.png' },
            { 'name': '拉斯帕尔马斯',   'logo': CONST['static']['url']+'images/fifa/team/laliga/lspems.png' },
            { 'name': '格拉纳达',       'logo': CONST['static']['url']+'images/fifa/team/laliga/glnd.png' },
            { 'name': '希洪竞技',       'logo': CONST['static']['url']+'images/fifa/team/laliga/xhjj.png' },
            { 'name': '莱加内斯',       'logo': CONST['static']['url']+'images/fifa/team/laliga/ljns.png' },
            { 'name': '阿拉维斯',       'logo': CONST['static']['url']+'images/fifa/team/laliga/alws.png' },
            { 'name': '奥萨苏纳',       'logo': CONST['static']['url']+'images/fifa/team/laliga/assn.png' },
        ],
    },
    {
        'name': '意甲', 'logo': CONST['static']['url']+'images/fifa/competition/seriea.png',
        'tags': [ 
            { 'name': 'AC米兰',     'logo': CONST['static']['url']+'images/fifa/team/seriea/acm.png' },
            { 'name': '国米',       'logo': CONST['static']['url']+'images/fifa/team/seriea/int.png' },
            { 'name': '尤文',       'logo': CONST['static']['url']+'images/fifa/team/seriea/juv.png' },
            { 'name': '罗马',       'logo': CONST['static']['url']+'images/fifa/team/seriea/rom.png' },
            { 'name': '那不勒斯',   'logo': CONST['static']['url']+'images/fifa/team/seriea/nap.png' },
            { 'name': '拉齐奥',     'logo': CONST['static']['url']+'images/fifa/team/seriea/lqa.png' },
            { 'name': '桑普多利亚', 'logo': CONST['static']['url']+'images/fifa/team/seriea/spdly.png' },
            { 'name': '切沃',       'logo': CONST['static']['url']+'images/fifa/team/seriea/qw.png' },
            { 'name': '乌迪内斯',   'logo': CONST['static']['url']+'images/fifa/team/seriea/wdns.png' },
            { 'name': '佛罗伦萨',   'logo': CONST['static']['url']+'images/fifa/team/seriea/flls.png' },
            { 'name': '亚特兰大',   'logo': CONST['static']['url']+'images/fifa/team/seriea/ytld.png' },
            { 'name': '巴勒莫',     'logo': CONST['static']['url']+'images/fifa/team/seriea/blm.png' },
            { 'name': '博洛尼亚',   'logo': CONST['static']['url']+'images/fifa/team/seriea/blny.png' },
            { 'name': '卡利亚里',   'logo': CONST['static']['url']+'images/fifa/team/seriea/klyl.png' },
            { 'name': '都灵',       'logo': CONST['static']['url']+'images/fifa/team/seriea/dl.png' },
            { 'name': '热那亚',     'logo': CONST['static']['url']+'images/fifa/team/seriea/rny.png' },
            { 'name': '萨索洛',     'logo': CONST['static']['url']+'images/fifa/team/seriea/ssl.png' },
            { 'name': '恩波利',     'logo': CONST['static']['url']+'images/fifa/team/seriea/ebl.png' },
            { 'name': '佩斯卡拉',   'logo': CONST['static']['url']+'images/fifa/team/seriea/pskl.png' },
            { 'name': '克罗托内',   'logo': CONST['static']['url']+'images/fifa/team/seriea/kltn.png' },
        ],
    },
    {
        'name': '德甲', 'logo': CONST['static']['url']+'images/fifa/competition/bundesliga.png',
        'tags': [
            { 'name': '拜仁',           'logo': CONST['static']['url']+'images/fifa/team/bundesliga/bm.png' },
            { 'name': '多特',           'logo': CONST['static']['url']+'images/fifa/team/bundesliga/bvb.png' },
            { 'name': '勒沃库森',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/lwks.png' },
            { 'name': '门兴德拉德巴赫', 'logo': CONST['static']['url']+'images/fifa/team/bundesliga/mxdldbh.png' },
            { 'name': '沃尔夫斯堡',     'logo': CONST['static']['url']+'images/fifa/team/bundesliga/wefsb.png' },
            { 'name': '美因茨',         'logo': CONST['static']['url']+'images/fifa/team/bundesliga/mec.png' },
            { 'name': '云达不莱梅',     'logo': CONST['static']['url']+'images/fifa/team/bundesliga/ydblm.png' },
            { 'name': '霍芬海姆',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/hfhm.png' },
            { 'name': '汉堡',           'logo': CONST['static']['url']+'images/fifa/team/bundesliga/hb.png' },
            { 'name': '科隆',           'logo': CONST['static']['url']+'images/fifa/team/bundesliga/kl.png' },
            { 'name': '沙尔克04',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/sek04.png' },
            { 'name': '柏林赫塔',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/blht.png' },
            { 'name': '因戈尔施塔特',   'logo': CONST['static']['url']+'images/fifa/team/bundesliga/ygestt.png' },
            { 'name': '达姆施塔特',     'logo': CONST['static']['url']+'images/fifa/team/bundesliga/dmstt.png' },
            { 'name': '奥格斯堡',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/agsb.png' },
            { 'name': '法兰克福',       'logo': CONST['static']['url']+'images/fifa/team/bundesliga/flkf.png' },
            { 'name': '莱比锡红牛',     'logo': CONST['static']['url']+'images/fifa/team/bundesliga/lbxhn.png' },
            { 'name': '弗赖堡',         'logo': CONST['static']['url']+'images/fifa/team/bundesliga/flb.png' },
        ],
    },
    {
        'name': '法甲', 'logo': CONST['static']['url']+'images/fifa/competition/ligue1.png',
        'tags': [ 
            { 'name': '巴黎圣日耳曼',   'logo': CONST['static']['url']+'images/fifa/team/ligue1/psg.png' },
            { 'name': '摩纳哥',         'logo': CONST['static']['url']+'images/fifa/team/ligue1/mng.png' },
            { 'name': '里昂',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/la.png' },
            { 'name': '波尔多',         'logo': CONST['static']['url']+'images/fifa/team/ligue1/bed.png' },
            { 'name': '尼斯',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/ns.png' },
            { 'name': '里尔',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/lier.png' },
            { 'name': '蒙彼利埃',       'logo': CONST['static']['url']+'images/fifa/team/ligue1/mbla.png' },
            { 'name': '昂热',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/ar.png' },
            { 'name': '洛里昂',         'logo': CONST['static']['url']+'images/fifa/team/ligue1/lla.png' },
            { 'name': '圣埃蒂安',       'logo': CONST['static']['url']+'images/fifa/team/ligue1/sada.png' },
            { 'name': '雷恩',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/leien.png' },
            { 'name': '马赛',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/masai.png' },
            { 'name': '卡昂',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/ka.png' },
            { 'name': '南特',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/nt.png' },
            { 'name': '巴斯蒂亚',       'logo': CONST['static']['url']+'images/fifa/team/ligue1/bsdy.png' },
            { 'name': '甘冈',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/gg.png' },
            { 'name': '图卢兹',         'logo': CONST['static']['url']+'images/fifa/team/ligue1/tlz.png' },
            { 'name': '梅斯',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/meisi.png' },
            { 'name': '南锡',           'logo': CONST['static']['url']+'images/fifa/team/ligue1/nx.png' },
        ],
    },
    {
        'name': '中甲', 'logo': CONST['static']['url']+'images/fifa/competition/cl1.png',
        'tags': [ 
            { 'name': '石家庄永昌',     'logo': CONST['static']['url']+'images/fifa/team/csl/sjzyc.png' },
            { 'name': '杭州绿城',       'logo': CONST['static']['url']+'images/fifa/team/csl/hzlc.png' },
            { 'name': '北京北控',       'logo': CONST['static']['url']+'images/fifa/team/cl1/bjbk.png' },
            { 'name': '大连一方',       'logo': CONST['static']['url']+'images/fifa/team/cl1/dlyf.png' },
            { 'name': '深圳佳兆业',     'logo': CONST['static']['url']+'images/fifa/team/cl1/szjzy.png' },
            { 'name': '上海申鑫',       'logo': CONST['static']['url']+'images/fifa/team/cl1/shsx.png' },
            { 'name': '北京人和',       'logo': CONST['static']['url']+'images/fifa/team/cl1/bjrh.png' },
            { 'name': '大连超越',       'logo': CONST['static']['url']+'images/fifa/team/cl1/dlcy.png' },
            { 'name': '青岛黄海',       'logo': CONST['static']['url']+'images/fifa/team/cl1/qdhh.png' },
            { 'name': '梅州客家',       'logo': CONST['static']['url']+'images/fifa/team/cl1/mzkj.png' },
            { 'name': '武汉卓尔',       'logo': CONST['static']['url']+'images/fifa/team/cl1/whze.png' },
            { 'name': '新疆天山雪豹',   'logo': CONST['static']['url']+'images/fifa/team/cl1/xjtsxb.png' },
            { 'name': '内蒙古中优',     'logo': CONST['static']['url']+'images/fifa/team/cl1/nmgzy.png' },
            { 'name': '浙江毅腾',       'logo': CONST['static']['url']+'images/fifa/team/cl1/zjyt.png' },
            #{ 'name': '丽江飞虎',      'logo': CONST['static']['url']+'images/fifa/team/cl1/ljfh.png' },
            #{ 'name': '保定容大',      'logo': CONST['static']['url']+'images/fifa/team/cl1/bdrd.png' },
            #{ 'name': '湖南湘涛华莱',   'logo': CONST['static']['url']+'images/fifa/team/cl1/hnxthl.png' },
            #{ 'name': '青岛中能',       'logo': CONST['static']['url']+'images/fifa/team/cl1/qdzn.png' },
        ],
    },
    {
        'name': '国家队', 'logo': CONST['static']['url']+'images/fifa/comprehensive/football_1.png',
        'tags': [ 
            { 'name': '中国',       'logo': CONST['static']['url']+'images/fifa/team/nation/china.png' },

            { 'name': '意大利',     'logo': CONST['static']['url']+'images/fifa/team/nation/italy.png' },
            { 'name': '比利时',     'logo': CONST['static']['url']+'images/fifa/team/nation/belgium.png' },
            { 'name': '英格兰',     'logo': CONST['static']['url']+'images/fifa/team/nation/england.png' },
            { 'name': '西班牙',     'logo': CONST['static']['url']+'images/fifa/team/nation/spain.png' },
            { 'name': '葡萄牙',     'logo': CONST['static']['url']+'images/fifa/team/nation/portugal.png' },
            { 'name': '克罗地亚',   'logo': CONST['static']['url']+'images/fifa/team/nation/croatia.png' },
            { 'name': '土耳其',     'logo': CONST['static']['url']+'images/fifa/team/nation/turkey.png' },
            { 'name': '荷兰',       'logo': CONST['static']['url']+'images/fifa/team/nation/netherlands.png' },
            { 'name': '德国',       'logo': CONST['static']['url']+'images/fifa/team/nation/german.png' },
            { 'name': '法国',       'logo': CONST['static']['url']+'images/fifa/team/nation/france.png' },
            { 'name': '乌克兰',     'logo': CONST['static']['url']+'images/fifa/team/nation/ukraine.png' },
            { 'name': '威尔士',     'logo': CONST['static']['url']+'images/fifa/team/nation/wales.png' },
            #{ 'name': '瑞士',       'logo': CONST['static']['url']+'images/fifa/team/nation/switzerland.png' },
            { 'name': '罗马尼亚',   'logo': CONST['static']['url']+'images/fifa/team/nation/romania.png' },
            #{ 'name': '阿尔巴尼亚', 'logo': CONST['static']['url']+'images/fifa/team/nation/albania.png' },
            { 'name': '俄罗斯',     'logo': CONST['static']['url']+'images/fifa/team/nation/russia.png' },
            #{ 'name': '斯洛伐克',   'logo': CONST['static']['url']+'images/fifa/team/nation/slovakia.png' },
            { 'name': '波兰',       'logo': CONST['static']['url']+'images/fifa/team/nation/poland.png' },
            { 'name': '北爱尔兰',   'logo': CONST['static']['url']+'images/fifa/team/nation/northernireland.png' },
            #{ 'name': '捷克',       'logo': CONST['static']['url']+'images/fifa/team/nation/czech.png' },
            #{ 'name': '爱尔兰',     'logo': CONST['static']['url']+'images/fifa/team/nation/ireland.png' },
            { 'name': '瑞典',       'logo': CONST['static']['url']+'images/fifa/team/nation/sweden.png' },
            { 'name': '冰岛',       'logo': CONST['static']['url']+'images/fifa/team/nation/iceland.png' },
            { 'name': '奥地利',     'logo': CONST['static']['url']+'images/fifa/team/nation/austria.png' },
            { 'name': '匈牙利',     'logo': CONST['static']['url']+'images/fifa/team/nation/hungary.png' },

            { 'name': '巴西',       'logo': CONST['static']['url']+'images/fifa/team/nation/brazil.png' },
            { 'name': '乌拉圭',     'logo': CONST['static']['url']+'images/fifa/team/nation/uruguay.png' },
            { 'name': '智利',       'logo': CONST['static']['url']+'images/fifa/team/nation/chile.png' },
            { 'name': '阿根廷',     'logo': CONST['static']['url']+'images/fifa/team/nation/argentina.png' },
            { 'name': '哥伦比亚',   'logo': CONST['static']['url']+'images/fifa/team/nation/columbia.png' },
            { 'name': '墨西哥',     'logo': CONST['static']['url']+'images/fifa/team/nation/mexico.png' },
            { 'name': '美国',       'logo': CONST['static']['url']+'images/fifa/team/nation/america.png' },
        ],
    },
]



